-- ============================================================
-- 智慧园区专家问答策略系统 - 完整数据库初始化脚本（从线上库导出）
-- 适用: PostgreSQL 15+（含 pgvector 扩展）
-- 执行方式: Supabase SQL Editor 或 psql -f db/init.sql
-- ============================================================

-- 扩展
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- RAG 向量相似度检索函数
CREATE OR REPLACE FUNCTION public.match_knowledge_chunks(query_embedding vector, match_document_ids integer[], match_count integer DEFAULT 3)
 RETURNS TABLE(id integer, document_id integer, content text, similarity double precision)
 LANGUAGE plpgsql
AS $function$
BEGIN
  RETURN QUERY
  SELECT
    kc.id,
    kc.document_id,
    kc.content,
    1 - (kc.embedding <=> query_embedding) AS similarity
  FROM knowledge_chunks kc
  WHERE kc.document_id = ANY(match_document_ids)
  ORDER BY kc.embedding <=> query_embedding
  LIMIT match_count;
END;
$function$
;

-- ================= TABLE: contacts =================
CREATE TABLE IF NOT EXISTS public.contacts (
    id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar NOT NULL,
    phone varchar,
    email varchar,
    department_id int4,
    position varchar,
    role varchar DEFAULT 'staff'::character varying,
    is_active bool DEFAULT true,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now(),
    PRIMARY KEY (id)
);
ALTER TABLE ONLY public.contacts ADD CONSTRAINT fk_contacts_department FOREIGN KEY (department_id) REFERENCES departments(id);

-- ================= TABLE: conversation_messages =================
CREATE TABLE IF NOT EXISTS public.conversation_messages (
    id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    conversation_id int4 NOT NULL,
    role varchar NOT NULL,
    content text NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb,
    token_count int4 DEFAULT 0,
    created_at timestamp DEFAULT now(),
    PRIMARY KEY (id)
);
ALTER TABLE ONLY public.conversation_messages ADD CONSTRAINT conversation_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE;

-- ================= TABLE: conversations =================
CREATE TABLE IF NOT EXISTS public.conversations (
    id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title varchar,
    user_id int4,
    knowledge_base_id int4,
    message_count int4 DEFAULT 0,
    status varchar DEFAULT 'active'::character varying,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now(),
    PRIMARY KEY (id)
);
ALTER TABLE ONLY public.conversations ADD CONSTRAINT conversations_knowledge_base_id_fkey FOREIGN KEY (knowledge_base_id) REFERENCES knowledge_bases(id);
ALTER TABLE ONLY public.conversations ADD CONSTRAINT conversations_user_id_fkey FOREIGN KEY (user_id) REFERENCES contacts(id);

-- ================= TABLE: dashboard_configs =================
CREATE TABLE IF NOT EXISTS public.dashboard_configs (
    id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar NOT NULL,
    description text,
    layout jsonb DEFAULT '[]'::jsonb,
    is_default bool DEFAULT false,
    is_active bool DEFAULT true,
    created_by int4,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now(),
    PRIMARY KEY (id)
);
ALTER TABLE ONLY public.dashboard_configs ADD CONSTRAINT dashboard_configs_created_by_fkey FOREIGN KEY (created_by) REFERENCES contacts(id);

-- ================= TABLE: departments =================
CREATE TABLE IF NOT EXISTS public.departments (
    id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar NOT NULL,
    parent_id int4,
    sort_order int4 DEFAULT 0,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now(),
    PRIMARY KEY (id)
);

-- ================= TABLE: device_sources =================
CREATE TABLE IF NOT EXISTS public.device_sources (
    id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar NOT NULL,
    db_type varchar NOT NULL DEFAULT 'postgres'::character varying,
    host varchar,
    port int4 DEFAULT 5432,
    database_name varchar,
    username varchar,
    password text,
    status varchar DEFAULT 'inactive'::character varying,
    last_connected_at timestamp,
    config_json jsonb DEFAULT '{}'::jsonb,
    created_by int4,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now(),
    PRIMARY KEY (id)
);
ALTER TABLE ONLY public.device_sources ADD CONSTRAINT device_sources_created_by_fkey FOREIGN KEY (created_by) REFERENCES contacts(id);

-- ================= TABLE: device_telemetry =================
CREATE TABLE IF NOT EXISTS public.device_telemetry (
    id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    device_id int4 NOT NULL,
    metric_key varchar NOT NULL,
    metric_value numeric,
    metric_unit varchar,
    status varchar DEFAULT 'normal'::character varying,
    collected_at timestamp DEFAULT now(),
    PRIMARY KEY (id)
);
ALTER TABLE ONLY public.device_telemetry ADD CONSTRAINT device_telemetry_device_id_fkey FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE;

-- ================= TABLE: devices =================
CREATE TABLE IF NOT EXISTS public.devices (
    id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_id int4,
    device_code varchar,
    device_name varchar NOT NULL,
    device_type varchar DEFAULT 'sensor'::character varying,
    location varchar,
    status varchar DEFAULT 'online'::character varying,
    description text,
    created_by int4,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now(),
    PRIMARY KEY (id)
);
ALTER TABLE ONLY public.devices ADD CONSTRAINT devices_device_code_key UNIQUE (device_code);
ALTER TABLE ONLY public.devices ADD CONSTRAINT devices_created_by_fkey FOREIGN KEY (created_by) REFERENCES contacts(id);
ALTER TABLE ONLY public.devices ADD CONSTRAINT devices_source_id_fkey FOREIGN KEY (source_id) REFERENCES device_sources(id) ON DELETE CASCADE;

-- ================= TABLE: emergency_plan_nodes =================
CREATE TABLE IF NOT EXISTS public.emergency_plan_nodes (
    id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    plan_id int4 NOT NULL,
    node_type varchar NOT NULL,
    node_name varchar NOT NULL,
    node_order int4 NOT NULL DEFAULT 0,
    config jsonb DEFAULT '{}'::jsonb,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now(),
    PRIMARY KEY (id)
);
ALTER TABLE ONLY public.emergency_plan_nodes ADD CONSTRAINT emergency_plan_nodes_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES emergency_plans(id) ON DELETE CASCADE;

-- ================= TABLE: emergency_plan_triggers =================
CREATE TABLE IF NOT EXISTS public.emergency_plan_triggers (
    id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    plan_id int4 NOT NULL,
    metric_type varchar NOT NULL,
    threshold numeric NOT NULL,
    operator varchar DEFAULT '>'::character varying,
    duration_seconds int4 DEFAULT 0,
    is_active bool DEFAULT true,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now(),
    PRIMARY KEY (id)
);
ALTER TABLE ONLY public.emergency_plan_triggers ADD CONSTRAINT emergency_plan_triggers_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES emergency_plans(id) ON DELETE CASCADE;

-- ================= TABLE: emergency_plans =================
CREATE TABLE IF NOT EXISTS public.emergency_plans (
    id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar NOT NULL,
    description text,
    category varchar NOT NULL DEFAULT 'fire'::character varying,
    level varchar DEFAULT 'medium'::character varying,
    status varchar DEFAULT 'draft'::character varying,
    created_by int4,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now(),
    PRIMARY KEY (id)
);
ALTER TABLE ONLY public.emergency_plans ADD CONSTRAINT fk_plans_creator FOREIGN KEY (created_by) REFERENCES contacts(id);

-- ================= TABLE: event_ai_reports =================
CREATE TABLE IF NOT EXISTS public.event_ai_reports (
    id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id int4 NOT NULL,
    summary text,
    timeline text,
    analysis text,
    suggestions text,
    generated_at timestamp DEFAULT now(),
    created_at timestamp DEFAULT now(),
    PRIMARY KEY (id)
);
ALTER TABLE ONLY public.event_ai_reports ADD CONSTRAINT event_ai_reports_event_id_fkey FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE;

-- ================= TABLE: event_node_progress =================
CREATE TABLE IF NOT EXISTS public.event_node_progress (
    id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id int4 NOT NULL,
    node_id int4,
    node_type varchar NOT NULL,
    node_name varchar,
    status varchar DEFAULT 'pending'::character varying,
    started_at timestamp,
    completed_at timestamp,
    operator_id int4,
    remark text,
    created_at timestamp DEFAULT now(),
    PRIMARY KEY (id)
);
ALTER TABLE ONLY public.event_node_progress ADD CONSTRAINT event_node_progress_event_id_fkey FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.event_node_progress ADD CONSTRAINT event_node_progress_node_id_fkey FOREIGN KEY (node_id) REFERENCES emergency_plan_nodes(id);
ALTER TABLE ONLY public.event_node_progress ADD CONSTRAINT fk_progress_operator FOREIGN KEY (operator_id) REFERENCES contacts(id);

-- ================= TABLE: event_notifications =================
CREATE TABLE IF NOT EXISTS public.event_notifications (
    id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id int4 NOT NULL,
    node_id int4,
    channel varchar NOT NULL,
    title varchar,
    content text,
    recipient_id int4,
    status varchar DEFAULT 'pending'::character varying,
    sent_at timestamp,
    delivered_at timestamp,
    error_message text,
    created_at timestamp DEFAULT now(),
    PRIMARY KEY (id)
);
ALTER TABLE ONLY public.event_notifications ADD CONSTRAINT event_notifications_event_id_fkey FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.event_notifications ADD CONSTRAINT event_notifications_node_id_fkey FOREIGN KEY (node_id) REFERENCES emergency_plan_nodes(id);
ALTER TABLE ONLY public.event_notifications ADD CONSTRAINT event_notifications_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES contacts(id);

-- ================= TABLE: event_tasks =================
CREATE TABLE IF NOT EXISTS public.event_tasks (
    id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id int4 NOT NULL,
    node_id int4,
    title varchar NOT NULL,
    description text,
    assignee_id int4,
    status varchar DEFAULT 'pending'::character varying,
    priority varchar DEFAULT 'medium'::character varying,
    due_at timestamp,
    completed_at timestamp,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now(),
    PRIMARY KEY (id)
);
ALTER TABLE ONLY public.event_tasks ADD CONSTRAINT event_tasks_assignee_id_fkey FOREIGN KEY (assignee_id) REFERENCES contacts(id);
ALTER TABLE ONLY public.event_tasks ADD CONSTRAINT event_tasks_event_id_fkey FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.event_tasks ADD CONSTRAINT event_tasks_node_id_fkey FOREIGN KEY (node_id) REFERENCES emergency_plan_nodes(id);

-- ================= TABLE: events =================
CREATE TABLE IF NOT EXISTS public.events (
    id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_no varchar,
    plan_id int4,
    title varchar NOT NULL,
    description text,
    level varchar DEFAULT 'medium'::character varying,
    status varchar DEFAULT 'active'::character varying,
    location varchar,
    trigger_type varchar DEFAULT 'auto'::character varying,
    started_at timestamp DEFAULT now(),
    resolved_at timestamp,
    closed_at timestamp,
    created_by int4,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now(),
    PRIMARY KEY (id)
);
ALTER TABLE ONLY public.events ADD CONSTRAINT events_event_no_key UNIQUE (event_no);
ALTER TABLE ONLY public.events ADD CONSTRAINT events_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES emergency_plans(id);
ALTER TABLE ONLY public.events ADD CONSTRAINT fk_events_creator FOREIGN KEY (created_by) REFERENCES contacts(id);

-- ================= TABLE: knowledge_bases =================
CREATE TABLE IF NOT EXISTS public.knowledge_bases (
    id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar NOT NULL,
    description text,
    category varchar DEFAULT 'fire_safety'::character varying,
    document_count int4 DEFAULT 0,
    chunk_count int4 DEFAULT 0,
    status varchar DEFAULT 'active'::character varying,
    created_by int4,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now(),
    PRIMARY KEY (id)
);
ALTER TABLE ONLY public.knowledge_bases ADD CONSTRAINT knowledge_bases_created_by_fkey FOREIGN KEY (created_by) REFERENCES contacts(id);

-- ================= TABLE: knowledge_chunks =================
CREATE TABLE IF NOT EXISTS public.knowledge_chunks (
    id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    document_id int4 NOT NULL,
    chunk_index int4 NOT NULL,
    content text NOT NULL,
    embedding vector(1024) NOT NULL,
    token_count int4 DEFAULT 0,
    created_at timestamp DEFAULT now(),
    PRIMARY KEY (id)
);
ALTER TABLE ONLY public.knowledge_chunks ADD CONSTRAINT knowledge_chunks_document_id_fkey FOREIGN KEY (document_id) REFERENCES knowledge_documents(id) ON DELETE CASCADE;
CREATE INDEX idx_knowledge_chunks_embedding ON public.knowledge_chunks USING hnsw (embedding vector_cosine_ops) WITH (m=16, ef_construction=64);

-- ================= TABLE: knowledge_documents =================
CREATE TABLE IF NOT EXISTS public.knowledge_documents (
    id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    knowledge_base_id int4 NOT NULL,
    title varchar NOT NULL,
    content text NOT NULL,
    source_type varchar DEFAULT 'text'::character varying,
    source_url varchar,
    word_count int4 DEFAULT 0,
    chunk_count int4 DEFAULT 0,
    status varchar DEFAULT 'processed'::character varying,
    created_by int4,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now(),
    PRIMARY KEY (id)
);
ALTER TABLE ONLY public.knowledge_documents ADD CONSTRAINT knowledge_documents_created_by_fkey FOREIGN KEY (created_by) REFERENCES contacts(id);
ALTER TABLE ONLY public.knowledge_documents ADD CONSTRAINT knowledge_documents_knowledge_base_id_fkey FOREIGN KEY (knowledge_base_id) REFERENCES knowledge_bases(id) ON DELETE CASCADE;

-- ================= TABLE: message_records =================
CREATE TABLE IF NOT EXISTS public.message_records (
    id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    channel varchar NOT NULL,
    title varchar,
    content text NOT NULL,
    status varchar DEFAULT 'pending'::character varying,
    template_id int4,
    contact_id int4,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now(),
    sent_at timestamp,
    delivered_at timestamp,
    error_message text,
    PRIMARY KEY (id)
);
ALTER TABLE ONLY public.message_records ADD CONSTRAINT fk_records_contact FOREIGN KEY (contact_id) REFERENCES contacts(id);
ALTER TABLE ONLY public.message_records ADD CONSTRAINT fk_records_template FOREIGN KEY (template_id) REFERENCES message_templates(id);

-- ================= TABLE: message_templates =================
CREATE TABLE IF NOT EXISTS public.message_templates (
    id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar NOT NULL,
    category varchar,
    channel varchar DEFAULT 'sms'::character varying,
    title_template varchar,
    content_template text NOT NULL,
    is_active bool DEFAULT true,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now(),
    variables text,
    PRIMARY KEY (id)
);

-- ================= TABLE: metric_mappings =================
CREATE TABLE IF NOT EXISTS public.metric_mappings (
    id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    device_source_id int4 NOT NULL,
    device_id int4,
    source_metric varchar NOT NULL,
    source_table varchar,
    metric_name varchar NOT NULL,
    metric_unit varchar,
    metric_type varchar DEFAULT 'value'::character varying,
    transform_rule text,
    alarm_threshold numeric,
    alarm_operator varchar DEFAULT '>'::character varying,
    is_active bool DEFAULT true,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now(),
    PRIMARY KEY (id)
);
ALTER TABLE ONLY public.metric_mappings ADD CONSTRAINT metric_mappings_device_id_fkey FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.metric_mappings ADD CONSTRAINT metric_mappings_device_source_id_fkey FOREIGN KEY (device_source_id) REFERENCES device_sources(id) ON DELETE CASCADE;

-- ================= TABLE: work_order_logs =================
CREATE TABLE IF NOT EXISTS public.work_order_logs (
    id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    work_order_id int4 NOT NULL,
    action varchar NOT NULL,
    operator_id int4,
    remark text,
    created_at timestamp DEFAULT now(),
    comment text,
    PRIMARY KEY (id)
);
ALTER TABLE ONLY public.work_order_logs ADD CONSTRAINT fk_logs_work_order FOREIGN KEY (work_order_id) REFERENCES work_orders(id);

-- ================= TABLE: work_orders =================
CREATE TABLE IF NOT EXISTS public.work_orders (
    id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title varchar NOT NULL,
    description text,
    type varchar DEFAULT 'fault'::character varying,
    priority varchar DEFAULT 'medium'::character varying,
    status varchar DEFAULT 'pending'::character varying,
    source varchar DEFAULT 'phone'::character varying,
    location varchar,
    creator_id int4,
    assignee_id int4,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now(),
    order_no varchar,
    expected_resolve_at timestamp,
    resolved_at timestamp,
    closed_at timestamp,
    PRIMARY KEY (id)
);
ALTER TABLE ONLY public.work_orders ADD CONSTRAINT fk_work_orders_assignee FOREIGN KEY (assignee_id) REFERENCES contacts(id);
ALTER TABLE ONLY public.work_orders ADD CONSTRAINT fk_work_orders_creator FOREIGN KEY (creator_id) REFERENCES contacts(id);

-- ============ 序列值校准 ============
SELECT setval('public.contacts_id_seq', COALESCE((SELECT MAX(id) FROM public.contacts), 1), true);
SELECT setval('public.conversation_messages_id_seq', COALESCE((SELECT MAX(id) FROM public.conversation_messages), 1), true);
SELECT setval('public.conversations_id_seq', COALESCE((SELECT MAX(id) FROM public.conversations), 1), true);
SELECT setval('public.dashboard_configs_id_seq', COALESCE((SELECT MAX(id) FROM public.dashboard_configs), 1), true);
SELECT setval('public.departments_id_seq', COALESCE((SELECT MAX(id) FROM public.departments), 1), true);
SELECT setval('public.device_sources_id_seq', COALESCE((SELECT MAX(id) FROM public.device_sources), 1), true);
SELECT setval('public.device_telemetry_id_seq', COALESCE((SELECT MAX(id) FROM public.device_telemetry), 1), true);
SELECT setval('public.devices_id_seq', COALESCE((SELECT MAX(id) FROM public.devices), 1), true);
SELECT setval('public.emergency_plan_nodes_id_seq', COALESCE((SELECT MAX(id) FROM public.emergency_plan_nodes), 1), true);
SELECT setval('public.emergency_plan_triggers_id_seq', COALESCE((SELECT MAX(id) FROM public.emergency_plan_triggers), 1), true);
SELECT setval('public.emergency_plans_id_seq', COALESCE((SELECT MAX(id) FROM public.emergency_plans), 1), true);
SELECT setval('public.event_ai_reports_id_seq', COALESCE((SELECT MAX(id) FROM public.event_ai_reports), 1), true);
SELECT setval('public.event_node_progress_id_seq', COALESCE((SELECT MAX(id) FROM public.event_node_progress), 1), true);
SELECT setval('public.event_notifications_id_seq', COALESCE((SELECT MAX(id) FROM public.event_notifications), 1), true);
SELECT setval('public.event_tasks_id_seq', COALESCE((SELECT MAX(id) FROM public.event_tasks), 1), true);
SELECT setval('public.events_id_seq', COALESCE((SELECT MAX(id) FROM public.events), 1), true);
SELECT setval('public.knowledge_bases_id_seq', COALESCE((SELECT MAX(id) FROM public.knowledge_bases), 1), true);
SELECT setval('public.knowledge_chunks_id_seq', COALESCE((SELECT MAX(id) FROM public.knowledge_chunks), 1), true);
SELECT setval('public.knowledge_documents_id_seq', COALESCE((SELECT MAX(id) FROM public.knowledge_documents), 1), true);
SELECT setval('public.message_records_id_seq', COALESCE((SELECT MAX(id) FROM public.message_records), 1), true);
SELECT setval('public.message_templates_id_seq', COALESCE((SELECT MAX(id) FROM public.message_templates), 1), true);
SELECT setval('public.metric_mappings_id_seq', COALESCE((SELECT MAX(id) FROM public.metric_mappings), 1), true);
SELECT setval('public.work_order_logs_id_seq', COALESCE((SELECT MAX(id) FROM public.work_order_logs), 1), true);
SELECT setval('public.work_orders_id_seq', COALESCE((SELECT MAX(id) FROM public.work_orders), 1), true);

-- ============ RLS 策略 ============
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversation_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dashboard_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.device_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.device_telemetry ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.emergency_plan_nodes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.emergency_plan_triggers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.emergency_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_ai_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_node_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.knowledge_bases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.knowledge_chunks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.knowledge_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.message_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.message_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.metric_mappings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_order_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_orders ENABLE ROW LEVEL SECURITY;

-- ============ 种子数据 ============
INSERT INTO public.departments ("id", "name", "parent_id", "sort_order", "created_at", "updated_at") VALUES (1, '物业管理部', NULL, 1, '2026-09-20T14:40:01.102642', '2026-09-20T14:40:01.102642') ON CONFLICT DO NOTHING;
INSERT INTO public.departments ("id", "name", "parent_id", "sort_order", "created_at", "updated_at") VALUES (2, '安保部', NULL, 2, '2026-09-20T14:40:01.102642', '2026-09-20T14:40:01.102642') ON CONFLICT DO NOTHING;
INSERT INTO public.departments ("id", "name", "parent_id", "sort_order", "created_at", "updated_at") VALUES (3, '运维部', NULL, 3, '2026-09-20T14:40:01.102642', '2026-09-20T14:40:01.102642') ON CONFLICT DO NOTHING;
INSERT INTO public.departments ("id", "name", "parent_id", "sort_order", "created_at", "updated_at") VALUES (4, '客服中心', NULL, 4, '2026-09-20T14:40:01.102642', '2026-09-20T14:40:01.102642') ON CONFLICT DO NOTHING;
INSERT INTO public.departments ("id", "name", "parent_id", "sort_order", "created_at", "updated_at") VALUES (5, '测试部门', NULL, 5, '2026-09-20T14:40:15.679815', '2026-09-20T14:40:15.679815') ON CONFLICT DO NOTHING;
INSERT INTO public.departments ("id", "name", "parent_id", "sort_order", "created_at", "updated_at") VALUES (6, '新部门', NULL, 10, '2026-09-20T14:40:54.918036', '2026-09-20T14:40:54.918036') ON CONFLICT DO NOTHING;

INSERT INTO public.contacts ("id", "name", "phone", "email", "department_id", "position", "role", "is_active", "created_at", "updated_at") VALUES (1, '王建国', '13800138001', 'wangjianguo@park.com', 1, '物业经理', 'admin', TRUE, '2026-09-20T14:40:01.102642', '2026-09-20T14:40:01.102642') ON CONFLICT DO NOTHING;
INSERT INTO public.contacts ("id", "name", "phone", "email", "department_id", "position", "role", "is_active", "created_at", "updated_at") VALUES (2, '李安全', '13800138002', 'lianquan@park.com', 2, '安保主管', 'admin', TRUE, '2026-09-20T14:40:01.102642', '2026-09-20T14:40:01.102642') ON CONFLICT DO NOTHING;
INSERT INTO public.contacts ("id", "name", "phone", "email", "department_id", "position", "role", "is_active", "created_at", "updated_at") VALUES (3, '张运维', '13800138003', 'zhangyunwei@park.com', 3, '运维工程师', 'staff', TRUE, '2026-09-20T14:40:01.102642', '2026-09-20T14:40:01.102642') ON CONFLICT DO NOTHING;
INSERT INTO public.contacts ("id", "name", "phone", "email", "department_id", "position", "role", "is_active", "created_at", "updated_at") VALUES (4, '陈客服', '13800138004', 'chenkefu@park.com', 4, '客服专员', 'staff', TRUE, '2026-09-20T14:40:01.102642', '2026-09-20T14:40:01.102642') ON CONFLICT DO NOTHING;
INSERT INTO public.contacts ("id", "name", "phone", "email", "department_id", "position", "role", "is_active", "created_at", "updated_at") VALUES (5, '赵巡检', '13800138005', 'zhaoxunjian@park.com', 2, '巡检员', 'staff', TRUE, '2026-09-20T14:40:01.102642', '2026-09-20T14:40:01.102642') ON CONFLICT DO NOTHING;
INSERT INTO public.contacts ("id", "name", "phone", "email", "department_id", "position", "role", "is_active", "created_at", "updated_at") VALUES (6, '测试联系人', '13900139000', 'test@park.com', 1, '测试员', 'staff', TRUE, '2026-09-20T14:40:15.721661', '2026-09-20T14:40:15.721661') ON CONFLICT DO NOTHING;
INSERT INTO public.contacts ("id", "name", "phone", "email", "department_id", "position", "role", "is_active", "created_at", "updated_at") VALUES (7, '新联系人', '13700137000', NULL, 1, '工程师', 'staff', TRUE, '2026-09-20T14:40:54.921986', '2026-09-20T14:40:54.921986') ON CONFLICT DO NOTHING;

INSERT INTO public.emergency_plans ("id", "name", "description", "category", "level", "status", "created_by", "created_at", "updated_at") VALUES (1, '火灾应急预案', '适用于园区建筑火灾的应急响应流程', 'fire', 'critical', 'active', 1, '2026-09-20T23:19:13.193653', '2026-09-20T23:19:13.193653') ON CONFLICT DO NOTHING;
INSERT INTO public.emergency_plans ("id", "name", "description", "category", "level", "status", "created_by", "created_at", "updated_at") VALUES (2, '电梯故障应急预案', '适用于电梯困人或故障的应急处置', 'equipment', 'high', 'active', 1, '2026-09-20T23:19:13.193653', '2026-09-20T23:19:13.193653') ON CONFLICT DO NOTHING;
INSERT INTO public.emergency_plans ("id", "name", "description", "category", "level", "status", "created_by", "created_at", "updated_at") VALUES (3, '安全入侵应急预案', '适用于非法入侵等安全事件', 'security', 'high', 'active', 2, '2026-09-20T23:19:13.193653', '2026-09-20T23:19:13.193653') ON CONFLICT DO NOTHING;

INSERT INTO public.message_templates ("id", "name", "category", "channel", "title_template", "content_template", "is_active", "created_at", "updated_at", "variables") VALUES (1, '火灾告警通知', 'emergency', 'sms', '【紧急】{{location}}火灾告警', '尊敬的{{name}}，{{location}}于{{time}}检测到火灾告警，请立即前往处理。', TRUE, '2026-09-20T14:40:01.102642', '2026-09-20T14:40:01.102642', NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.message_templates ("id", "name", "category", "channel", "title_template", "content_template", "is_active", "created_at", "updated_at", "variables") VALUES (2, '设备故障通知', 'fault', 'sms', '【故障】{{location}}设备异常', '尊敬的{{name}}，{{location}}设备于{{time}}发生故障，请及时维修。', TRUE, '2026-09-20T14:40:01.102642', '2026-09-20T14:40:01.102642', NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.message_templates ("id", "name", "category", "channel", "title_template", "content_template", "is_active", "created_at", "updated_at", "variables") VALUES (3, '巡检提醒', 'inspection', 'app', '巡检任务提醒', '您好，您有一条新的巡检任务，请及时完成。', TRUE, '2026-09-20T14:40:01.102642', '2026-09-20T14:40:01.102642', NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.message_templates ("id", "name", "category", "channel", "title_template", "content_template", "is_active", "created_at", "updated_at", "variables") VALUES (4, '工单分配通知', 'work_order', 'sms', '新工单分配', '您有一个新的工单：{{title}}，请及时处理。', TRUE, '2026-09-20T14:40:01.102642', '2026-09-20T14:40:01.102642', NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.message_templates ("id", "name", "category", "channel", "title_template", "content_template", "is_active", "created_at", "updated_at", "variables") VALUES (5, '新模板', 'test', 'sms', NULL, '测试内容', TRUE, '2026-09-20T14:40:54.939494', '2026-09-20T14:40:54.939494', NULL) ON CONFLICT DO NOTHING;

INSERT INTO public.knowledge_bases ("id", "name", "description", "category", "document_count", "chunk_count", "status", "created_by", "created_at", "updated_at") VALUES (1, '火灾应急知识库', '包含火灾应急处置流程、消防设施使用、疏散指南等知识', 'fire_safety', 0, 0, 'active', 1, '2026-09-22T13:26:50.381250', '2026-09-22T13:26:50.381250') ON CONFLICT DO NOTHING;
INSERT INTO public.knowledge_bases ("id", "name", "description", "category", "document_count", "chunk_count", "status", "created_by", "created_at", "updated_at") VALUES (2, '设备维护知识库', '包含园区设备维护手册、故障排查指南等', 'equipment', 0, 0, 'active', 1, '2026-09-22T13:26:50.381250', '2026-09-22T13:26:50.381250') ON CONFLICT DO NOTHING;
INSERT INTO public.knowledge_bases ("id", "name", "description", "category", "document_count", "chunk_count", "status", "created_by", "created_at", "updated_at") VALUES (3, '安全管理知识库', '包含安全管理制度、应急预案模板等', 'safety', 0, 0, 'active', 2, '2026-09-22T13:26:50.381250', '2026-09-22T13:26:50.381250') ON CONFLICT DO NOTHING;

INSERT INTO public.device_sources ("id", "name", "db_type", "host", "port", "database_name", "username", "password", "status", "last_connected_at", "config_json", "created_by", "created_at", "updated_at") VALUES (1, '园区消防物联网平台', 'postgres', '10.0.0.100', 5432, 'fire_iot', 'iot_user', 'iot_pass', 'connected', '2026-09-22T06:22:11.962000', '{"driver":"postgresql","timeout_seconds":5}', 1, '2026-09-22T14:18:27.757130', '2026-09-22T06:22:11.962000') ON CONFLICT DO NOTHING;
INSERT INTO public.device_sources ("id", "name", "db_type", "host", "port", "database_name", "username", "password", "status", "last_connected_at", "config_json", "created_by", "created_at", "updated_at") VALUES (2, '楼宇自控系统', 'postgres', '10.0.0.101', 5432, 'bas_db', 'bas_user', 'bas_pass', 'active', NULL, '{"driver":"postgresql","timeout_seconds":5}', 1, '2026-09-22T14:18:27.757130', '2026-09-22T14:18:27.757130') ON CONFLICT DO NOTHING;
INSERT INTO public.device_sources ("id", "name", "db_type", "host", "port", "database_name", "username", "password", "status", "last_connected_at", "config_json", "created_by", "created_at", "updated_at") VALUES (3, '安防监控平台', 'mysql', '10.0.0.102', 3306, 'security_db', 'sec_user', 'sec_pass', 'inactive', NULL, '{"driver":"mysql","timeout_seconds":10}', 2, '2026-09-22T14:18:27.757130', '2026-09-22T14:18:27.757130') ON CONFLICT DO NOTHING;
INSERT INTO public.device_sources ("id", "name", "db_type", "host", "port", "database_name", "username", "password", "status", "last_connected_at", "config_json", "created_by", "created_at", "updated_at") VALUES (4, '新增数据源', 'postgres', 'test', 5432, 'test_db', 'u', 'p', 'inactive', NULL, '{}', NULL, '2026-09-22T14:22:11.535963', '2026-09-22T14:22:11.535963') ON CONFLICT DO NOTHING;

INSERT INTO public.work_orders ("id", "title", "description", "type", "priority", "status", "source", "location", "creator_id", "assignee_id", "created_at", "updated_at", "order_no", "expected_resolve_at", "resolved_at", "closed_at") VALUES (1, 'A栋电梯故障', 'A栋2号电梯运行异常，有异响', 'fault', 'high', 'in_progress', 'phone', 'A栋2号电梯', 1, 3, '2026-09-20T14:40:01.102642', '2026-09-20T14:40:01.102642', NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.work_orders ("id", "title", "description", "type", "priority", "status", "source", "location", "creator_id", "assignee_id", "created_at", "updated_at", "order_no", "expected_resolve_at", "resolved_at", "closed_at") VALUES (2, 'B栋消防通道堵塞', 'B栋消防通道被杂物堵塞', 'fault', 'medium', 'pending', 'app', 'B栋消防通道', 2, 5, '2026-09-20T14:40:01.102642', '2026-09-20T14:40:01.102642', NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.work_orders ("id", "title", "description", "type", "priority", "status", "source", "location", "creator_id", "assignee_id", "created_at", "updated_at", "order_no", "expected_resolve_at", "resolved_at", "closed_at") VALUES (3, '园区路灯维修', 'C栋周边3盏路灯不亮', 'maintenance', 'low', 'completed', 'phone', 'C栋周边', 1, 3, '2026-09-20T14:40:01.102642', '2026-09-20T14:40:01.102642', NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.work_orders ("id", "title", "description", "type", "priority", "status", "source", "location", "creator_id", "assignee_id", "created_at", "updated_at", "order_no", "expected_resolve_at", "resolved_at", "closed_at") VALUES (4, '新工单', '测试工单', 'fault', 'high', 'pending', 'phone', 'A栋', NULL, NULL, '2026-09-20T14:40:54.940668', '2026-09-20T14:40:54.940668', 'WO20260920144054', NULL, NULL, NULL) ON CONFLICT DO NOTHING;

INSERT INTO public.message_records ("id", "channel", "title", "content", "status", "template_id", "contact_id", "created_at", "updated_at", "sent_at", "delivered_at", "error_message") VALUES (1, 'sms', '【紧急】A栋3楼火灾告警', '尊敬的张运维，A栋3楼于14:30检测到火灾告警，请立即前往处理。', 'sent', 1, 3, '2026-09-20T14:40:01.102642', '2026-09-20T14:40:01.102642', NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.message_records ("id", "channel", "title", "content", "status", "template_id", "contact_id", "created_at", "updated_at", "sent_at", "delivered_at", "error_message") VALUES (2, 'sms', '【故障】B栋电梯故障', '尊敬的张运维，B栋1号电梯于10:15发生故障，请及时维修。', 'sent', 2, 3, '2026-09-20T14:40:01.102642', '2026-09-20T14:40:01.102642', NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.message_records ("id", "channel", "title", "content", "status", "template_id", "contact_id", "created_at", "updated_at", "sent_at", "delivered_at", "error_message") VALUES (3, 'app', '巡检任务提醒', '您好，您有一条新的巡检任务，请及时完成。', 'read', 3, 5, '2026-09-20T14:40:01.102642', '2026-09-20T14:40:01.102642', NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.message_records ("id", "channel", "title", "content", "status", "template_id", "contact_id", "created_at", "updated_at", "sent_at", "delivered_at", "error_message") VALUES (4, 'sms', '新工单分配', '您有一个新的工单：A栋电梯故障，请及时处理。', 'pending', 4, 3, '2026-09-20T14:40:01.102642', '2026-09-20T14:40:01.102642', NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.message_records ("id", "channel", "title", "content", "status", "template_id", "contact_id", "created_at", "updated_at", "sent_at", "delivered_at", "error_message") VALUES (5, 'sms', '测试消息', '测试消息内容', 'pending', NULL, NULL, '2026-09-20T14:40:15.671003', '2026-09-20T14:40:15.671003', NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.message_records ("id", "channel", "title", "content", "status", "template_id", "contact_id", "created_at", "updated_at", "sent_at", "delivered_at", "error_message") VALUES (6, 'sms', '新消息', '消息内容', 'pending', NULL, NULL, '2026-09-20T14:40:54.951724', '2026-09-20T14:40:54.951724', NULL, NULL, NULL) ON CONFLICT DO NOTHING;

INSERT INTO public.work_order_logs ("id", "work_order_id", "action", "operator_id", "remark", "created_at", "comment") VALUES (1, 1, 'created', 1, '创建工单', '2026-09-20T14:40:01.102642', NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.work_order_logs ("id", "work_order_id", "action", "operator_id", "remark", "created_at", "comment") VALUES (2, 1, 'assigned', 1, '分配给张运维', '2026-09-20T14:40:01.102642', NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.work_order_logs ("id", "work_order_id", "action", "operator_id", "remark", "created_at", "comment") VALUES (3, 1, 'in_progress', 3, '开始处理', '2026-09-20T14:40:01.102642', NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.work_order_logs ("id", "work_order_id", "action", "operator_id", "remark", "created_at", "comment") VALUES (4, 2, 'created', 2, '创建工单', '2026-09-20T14:40:01.102642', NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.work_order_logs ("id", "work_order_id", "action", "operator_id", "remark", "created_at", "comment") VALUES (5, 3, 'created', 1, '创建工单', '2026-09-20T14:40:01.102642', NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.work_order_logs ("id", "work_order_id", "action", "operator_id", "remark", "created_at", "comment") VALUES (6, 3, 'completed', 3, '已维修完成', '2026-09-20T14:40:01.102642', NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.work_order_logs ("id", "work_order_id", "action", "operator_id", "remark", "created_at", "comment") VALUES (7, 4, 'created', NULL, NULL, '2026-09-20T14:40:54.974461', '测试工单') ON CONFLICT DO NOTHING;

INSERT INTO public.knowledge_documents ("id", "knowledge_base_id", "title", "content", "source_type", "source_url", "word_count", "chunk_count", "status", "created_by", "created_at", "updated_at") VALUES (1, 1, '火灾应急处置流程', '一、发现火情后的第一时间处置：
1. 立即按下最近的手动火灾报警按钮
2. 拨打119报警电话，说明详细地址、起火部位、火势大小
3. 使用附近灭火器进行初期扑救（仅限小火）
4. 组织附近人员疏散

二、灭火器使用方法（PASS法则）：
- P（Pull）：拔掉保险销
- A（Aim）：瞄准火源根部
- S（Squeeze）：压下手柄
- S（Sweep）：左右扫射

三、疏散逃生要点：
1. 保持冷静，不要乘坐电梯
2. 用湿毛巾捂住口鼻，低姿前进
3. 沿疏散指示标志方向逃生
4. 身上着火时就地打滚

四、火灾分类：
- A类：固体物质火灾（木材、纸张等）
- B类：液体火灾（汽油、酒精等）
- C类：气体火灾（天然气、液化气等）
- D类：金属火灾
- E类：带电火灾
- F类：烹饪油脂火灾', 'text', NULL, 380, 4, 'processed', 1, '2026-09-22T13:26:50.381250', '2026-09-22T13:26:50.381250') ON CONFLICT DO NOTHING;
INSERT INTO public.knowledge_documents ("id", "knowledge_base_id", "title", "content", "source_type", "source_url", "word_count", "chunk_count", "status", "created_by", "created_at", "updated_at") VALUES (2, 1, '消防设施使用说明', '一、灭火器类型及适用范围：
1. 干粉灭火器：适用于A、B、C、E类火灾，最常见
2. 二氧化碳灭火器：适用于B、E类火灾，不留残留物
3. 泡沫灭火器：适用于A、B类火灾
4. 水基灭火器：适用于A类火灾

二、消火栓使用方法：
1. 打开消火栓箱门
2. 取出水带并展开
3. 将水带接口连接消火栓出水口
4. 另一端的接口连接水枪
5. 按下启泵按钮
6. 逆时针打开消火栓阀门
7. 握紧水枪对准火源根部射水

三、自动喷水灭火系统：
- 当环境温度达到68°C时，喷头玻璃球自动爆裂喷水
- 严禁在喷头下方堆放物品
- 发现喷头损坏应及时报修

四、防排烟系统：
- 火灾时自动启动，排出有毒烟气
- 楼梯间正压送风，防止烟气进入
- 严禁堵塞排烟口', 'text', NULL, 350, 4, 'processed', 1, '2026-09-22T13:26:50.381250', '2026-09-22T13:26:50.381250') ON CONFLICT DO NOTHING;
INSERT INTO public.knowledge_documents ("id", "knowledge_base_id", "title", "content", "source_type", "source_url", "word_count", "chunk_count", "status", "created_by", "created_at", "updated_at") VALUES (3, 1, '园区火灾应急预案', '一、预案目的：
规范园区火灾应急处置流程，最大限度减少人员伤亡和财产损失。

二、组织架构：
- 总指挥：物业经理
- 副总指挥：安保主管
- 灭火行动组：安保人员
- 疏散引导组：各楼层负责人
- 医疗救护组：受过急救培训的人员
- 后勤保障组：运维人员

三、应急响应流程：
1. 发现火情 → 立即报警 → 启动预案
2. 灭火行动组携带灭火器材赶赴现场
3. 疏散引导组组织人员有序疏散
4. 后勤保障组确保消防设备正常运行
5. 火势无法控制时，全员撤离等待消防队

四、报警电话：
- 火警：119
- 园区安保中心：8888
- 物业值班室：9999

五、集合地点：
- A栋人员：A栋前广场
- B栋人员：B栋侧门空地
- C栋人员：园区中心花园', 'text', NULL, 320, 3, 'processed', 1, '2026-09-22T13:26:50.381250', '2026-09-22T13:26:50.381250') ON CONFLICT DO NOTHING;

INSERT INTO public.devices ("id", "source_id", "device_code", "device_name", "device_type", "location", "status", "description", "created_by", "created_at", "updated_at") VALUES (1, 1, 'SMOKE-A3-001', 'A栋3楼烟雾探测器', 'sensor', 'A栋3楼走廊', 'online', NULL, NULL, '2026-09-22T14:18:27.757130', '2026-09-22T14:18:27.757130') ON CONFLICT DO NOTHING;
INSERT INTO public.devices ("id", "source_id", "device_code", "device_name", "device_type", "location", "status", "description", "created_by", "created_at", "updated_at") VALUES (2, 1, 'SMOKE-A4-002', 'A栋4楼烟雾探测器', 'sensor', 'A栋4楼走廊', 'online', NULL, NULL, '2026-09-22T14:18:27.757130', '2026-09-22T14:18:27.757130') ON CONFLICT DO NOTHING;
INSERT INTO public.devices ("id", "source_id", "device_code", "device_name", "device_type", "location", "status", "description", "created_by", "created_at", "updated_at") VALUES (3, 1, 'TEMP-B1-001', 'B栋1楼温度传感器', 'sensor', 'B栋1楼机房', 'online', NULL, NULL, '2026-09-22T14:18:27.757130', '2026-09-22T14:18:27.757130') ON CONFLICT DO NOTHING;
INSERT INTO public.devices ("id", "source_id", "device_code", "device_name", "device_type", "location", "status", "description", "created_by", "created_at", "updated_at") VALUES (4, 2, 'HVAC-C2-001', 'C栋2楼空调机组', 'device', 'C栋2楼设备间', 'online', NULL, NULL, '2026-09-22T14:18:27.757130', '2026-09-22T14:18:27.757130') ON CONFLICT DO NOTHING;
INSERT INTO public.devices ("id", "source_id", "device_code", "device_name", "device_type", "location", "status", "description", "created_by", "created_at", "updated_at") VALUES (5, 2, 'ELEV-B1-01', 'B栋1号电梯', 'device', 'B栋', 'online', NULL, NULL, '2026-09-22T14:18:27.757130', '2026-09-22T14:18:27.757130') ON CONFLICT DO NOTHING;
INSERT INTO public.devices ("id", "source_id", "device_code", "device_name", "device_type", "location", "status", "description", "created_by", "created_at", "updated_at") VALUES (6, 3, 'CAM-A1-001', 'A栋1楼摄像头', 'camera', 'A栋1楼大厅', 'online', NULL, NULL, '2026-09-22T14:18:27.757130', '2026-09-22T14:18:27.757130') ON CONFLICT DO NOTHING;

INSERT INTO public.metric_mappings ("id", "device_source_id", "device_id", "source_metric", "source_table", "metric_name", "metric_unit", "metric_type", "transform_rule", "alarm_threshold", "alarm_operator", "is_active", "created_at", "updated_at") VALUES (1, 1, 1, 'smoke_level', 'smoke_readings', '烟雾浓度', 'ppm', 'value', NULL, '80.00', '>', TRUE, '2026-09-22T14:18:27.757130', '2026-09-22T14:18:27.757130') ON CONFLICT DO NOTHING;
INSERT INTO public.metric_mappings ("id", "device_source_id", "device_id", "source_metric", "source_table", "metric_name", "metric_unit", "metric_type", "transform_rule", "alarm_threshold", "alarm_operator", "is_active", "created_at", "updated_at") VALUES (2, 1, 1, 'smoke_status', 'smoke_readings', '烟雾状态', NULL, 'status', NULL, NULL, NULL, TRUE, '2026-09-22T14:18:27.757130', '2026-09-22T14:18:27.757130') ON CONFLICT DO NOTHING;
INSERT INTO public.metric_mappings ("id", "device_source_id", "device_id", "source_metric", "source_table", "metric_name", "metric_unit", "metric_type", "transform_rule", "alarm_threshold", "alarm_operator", "is_active", "created_at", "updated_at") VALUES (3, 1, 2, 'smoke_level', 'smoke_readings', '烟雾浓度', 'ppm', 'value', NULL, '80.00', '>', TRUE, '2026-09-22T14:18:27.757130', '2026-09-22T14:18:27.757130') ON CONFLICT DO NOTHING;
INSERT INTO public.metric_mappings ("id", "device_source_id", "device_id", "source_metric", "source_table", "metric_name", "metric_unit", "metric_type", "transform_rule", "alarm_threshold", "alarm_operator", "is_active", "created_at", "updated_at") VALUES (4, 1, 3, 'temperature', 'temp_readings', '温度', '°C', 'value', NULL, '60.00', '>', TRUE, '2026-09-22T14:18:27.757130', '2026-09-22T14:18:27.757130') ON CONFLICT DO NOTHING;
INSERT INTO public.metric_mappings ("id", "device_source_id", "device_id", "source_metric", "source_table", "metric_name", "metric_unit", "metric_type", "transform_rule", "alarm_threshold", "alarm_operator", "is_active", "created_at", "updated_at") VALUES (5, 2, 4, 'power_consumption', 'hvac_metrics', '能耗', 'kWh', 'counter', '/100', NULL, NULL, TRUE, '2026-09-22T14:18:27.757130', '2026-09-22T14:18:27.757130') ON CONFLICT DO NOTHING;
INSERT INTO public.metric_mappings ("id", "device_source_id", "device_id", "source_metric", "source_table", "metric_name", "metric_unit", "metric_type", "transform_rule", "alarm_threshold", "alarm_operator", "is_active", "created_at", "updated_at") VALUES (6, 2, 5, 'elevator_speed', 'elevator_metrics', '电梯速度', 'm/s', 'value', NULL, NULL, NULL, TRUE, '2026-09-22T14:18:27.757130', '2026-09-22T14:18:27.757130') ON CONFLICT DO NOTHING;
INSERT INTO public.metric_mappings ("id", "device_source_id", "device_id", "source_metric", "source_table", "metric_name", "metric_unit", "metric_type", "transform_rule", "alarm_threshold", "alarm_operator", "is_active", "created_at", "updated_at") VALUES (7, 3, 6, 'camera_status', NULL, '摄像头状态', NULL, 'status', NULL, NULL, '>', TRUE, '2026-09-22T14:22:11.536223', '2026-09-22T14:22:11.536223') ON CONFLICT DO NOTHING;

INSERT INTO public.device_telemetry ("id", "device_id", "metric_key", "metric_value", "metric_unit", "status", "collected_at") VALUES (1, 1, 'smoke_level', '65.5000', 'ppm', 'normal', '2026-09-22T14:13:27.757130') ON CONFLICT DO NOTHING;
INSERT INTO public.device_telemetry ("id", "device_id", "metric_key", "metric_value", "metric_unit", "status", "collected_at") VALUES (2, 1, 'smoke_level', '72.3000', 'ppm', 'normal', '2026-09-22T14:14:27.757130') ON CONFLICT DO NOTHING;
INSERT INTO public.device_telemetry ("id", "device_id", "metric_key", "metric_value", "metric_unit", "status", "collected_at") VALUES (3, 1, 'smoke_level', '78.1000', 'ppm', 'warning', '2026-09-22T14:15:27.757130') ON CONFLICT DO NOTHING;
INSERT INTO public.device_telemetry ("id", "device_id", "metric_key", "metric_value", "metric_unit", "status", "collected_at") VALUES (4, 1, 'smoke_level', '85.6000', 'ppm', 'alarm', '2026-09-22T14:16:27.757130') ON CONFLICT DO NOTHING;
INSERT INTO public.device_telemetry ("id", "device_id", "metric_key", "metric_value", "metric_unit", "status", "collected_at") VALUES (5, 1, 'smoke_level', '92.4000', 'ppm', 'alarm', '2026-09-22T14:17:27.757130') ON CONFLICT DO NOTHING;
INSERT INTO public.device_telemetry ("id", "device_id", "metric_key", "metric_value", "metric_unit", "status", "collected_at") VALUES (6, 1, 'smoke_level', '88.2000', 'ppm', 'alarm', '2026-09-22T14:18:27.757130') ON CONFLICT DO NOTHING;
INSERT INTO public.device_telemetry ("id", "device_id", "metric_key", "metric_value", "metric_unit", "status", "collected_at") VALUES (7, 3, 'temperature', '58.2000', '°C', 'normal', '2026-09-22T14:13:27.757130') ON CONFLICT DO NOTHING;
INSERT INTO public.device_telemetry ("id", "device_id", "metric_key", "metric_value", "metric_unit", "status", "collected_at") VALUES (8, 3, 'temperature', '61.5000', '°C', 'warning', '2026-09-22T14:14:27.757130') ON CONFLICT DO NOTHING;
INSERT INTO public.device_telemetry ("id", "device_id", "metric_key", "metric_value", "metric_unit", "status", "collected_at") VALUES (9, 3, 'temperature', '59.8000', '°C', 'normal', '2026-09-22T14:15:27.757130') ON CONFLICT DO NOTHING;
INSERT INTO public.device_telemetry ("id", "device_id", "metric_key", "metric_value", "metric_unit", "status", "collected_at") VALUES (10, 3, 'temperature', '63.2000', '°C', 'alarm', '2026-09-22T14:16:27.757130') ON CONFLICT DO NOTHING;
INSERT INTO public.device_telemetry ("id", "device_id", "metric_key", "metric_value", "metric_unit", "status", "collected_at") VALUES (11, 3, 'temperature', '60.5000', '°C', 'warning', '2026-09-22T14:17:27.757130') ON CONFLICT DO NOTHING;
INSERT INTO public.device_telemetry ("id", "device_id", "metric_key", "metric_value", "metric_unit", "status", "collected_at") VALUES (12, 3, 'temperature', '62.1000', '°C', 'alarm', '2026-09-22T14:18:27.757130') ON CONFLICT DO NOTHING;

INSERT INTO public.dashboard_configs ("id", "name", "description", "layout", "is_default", "is_active", "created_by", "created_at", "updated_at") VALUES (1, '园区消防监控看板', '园区消防设备实时监控看板', '[{"widget":"device_status","position":0},{"widget":"metric_alerts","position":1},{"widget":"smoke_chart","position":2},{"widget":"temperature_chart","position":3}]', TRUE, TRUE, 1, '2026-09-22T14:18:27.757130', '2026-09-22T14:18:27.757130') ON CONFLICT DO NOTHING;
INSERT INTO public.dashboard_configs ("id", "name", "description", "layout", "is_default", "is_active", "created_by", "created_at", "updated_at") VALUES (2, '能耗监控看板', '园区能耗实时监控看板', '[{"widget":"device_status","position":0},{"widget":"power_chart","position":1}]', FALSE, TRUE, 1, '2026-09-22T14:18:27.757130', '2026-09-22T14:18:27.757130') ON CONFLICT DO NOTHING;

INSERT INTO public.emergency_plan_nodes ("id", "plan_id", "node_type", "node_name", "node_order", "config", "created_at", "updated_at") VALUES (1, 1, 'trigger', '火警触发', 1, '{"description":"检测到火灾信号自动触发或人工确认触发"}', '2026-09-20T23:19:13.193653', '2026-09-20T23:19:13.193653') ON CONFLICT DO NOTHING;
INSERT INTO public.emergency_plan_nodes ("id", "plan_id", "node_type", "node_name", "node_order", "config", "created_at", "updated_at") VALUES (2, 1, 'notification', '通知相关人员', 2, '{"targets":["物业经理","安保主管","运维工程师"],"channels":["sms","app"]}', '2026-09-20T23:19:13.193653', '2026-09-20T23:19:13.193653') ON CONFLICT DO NOTHING;
INSERT INTO public.emergency_plan_nodes ("id", "plan_id", "node_type", "node_name", "node_order", "config", "created_at", "updated_at") VALUES (3, 1, 'task', '现场处置任务', 3, '{"tasks":["确认火情","疏散人员","启动消防设备"]}', '2026-09-20T23:19:13.193653', '2026-09-20T23:19:13.193653') ON CONFLICT DO NOTHING;
INSERT INTO public.emergency_plan_nodes ("id", "plan_id", "node_type", "node_name", "node_order", "config", "created_at", "updated_at") VALUES (4, 1, 'escalation', '人工升级确认', 4, '{"description":"现场人员确认是否需要升级响应","timeout_minutes":5}', '2026-09-20T23:19:13.193653', '2026-09-20T23:19:13.193653') ON CONFLICT DO NOTHING;
INSERT INTO public.emergency_plan_nodes ("id", "plan_id", "node_type", "node_name", "node_order", "config", "created_at", "updated_at") VALUES (5, 1, 'end', '事件结束', 5, '{"description":"火情解除，记录复盘"}', '2026-09-20T23:19:13.193653', '2026-09-20T23:19:13.193653') ON CONFLICT DO NOTHING;
INSERT INTO public.emergency_plan_nodes ("id", "plan_id", "node_type", "node_name", "node_order", "config", "created_at", "updated_at") VALUES (6, 2, 'trigger', '电梯故障触发', 1, '{"description":"电梯故障信号触发"}', '2026-09-20T23:19:13.193653', '2026-09-20T23:19:13.193653') ON CONFLICT DO NOTHING;
INSERT INTO public.emergency_plan_nodes ("id", "plan_id", "node_type", "node_name", "node_order", "config", "created_at", "updated_at") VALUES (7, 2, 'notification', '通知维保人员', 2, '{"targets":["运维工程师"],"channels":["sms"]}', '2026-09-20T23:19:13.193653', '2026-09-20T23:19:13.193653') ON CONFLICT DO NOTHING;
INSERT INTO public.emergency_plan_nodes ("id", "plan_id", "node_type", "node_name", "node_order", "config", "created_at", "updated_at") VALUES (8, 2, 'task', '救援任务', 3, '{"tasks":["确认困人情况","联系维保","现场安抚"]}', '2026-09-20T23:19:13.193653', '2026-09-20T23:19:13.193653') ON CONFLICT DO NOTHING;
INSERT INTO public.emergency_plan_nodes ("id", "plan_id", "node_type", "node_name", "node_order", "config", "created_at", "updated_at") VALUES (9, 2, 'end', '事件结束', 4, '{"description":"故障排除，记录归档"}', '2026-09-20T23:19:13.193653', '2026-09-20T23:19:13.193653') ON CONFLICT DO NOTHING;

INSERT INTO public.emergency_plan_triggers ("id", "plan_id", "metric_type", "threshold", "operator", "duration_seconds", "is_active", "created_at", "updated_at") VALUES (1, 1, 'smoke_level', '80.00', '>', 30, TRUE, '2026-09-20T23:19:13.193653', '2026-09-20T23:19:13.193653') ON CONFLICT DO NOTHING;
INSERT INTO public.emergency_plan_triggers ("id", "plan_id", "metric_type", "threshold", "operator", "duration_seconds", "is_active", "created_at", "updated_at") VALUES (2, 1, 'temperature', '60.00', '>', 10, TRUE, '2026-09-20T23:19:13.193653', '2026-09-20T23:19:13.193653') ON CONFLICT DO NOTHING;
INSERT INTO public.emergency_plan_triggers ("id", "plan_id", "metric_type", "threshold", "operator", "duration_seconds", "is_active", "created_at", "updated_at") VALUES (3, 1, 'flame_detected', '1.00', '=', 0, TRUE, '2026-09-20T23:19:13.193653', '2026-09-20T23:19:13.193653') ON CONFLICT DO NOTHING;

INSERT INTO public.conversations ("id", "title", "user_id", "knowledge_base_id", "message_count", "status", "created_at", "updated_at") VALUES (1, '测试对话', NULL, 1, 3, 'active', '2026-09-22T13:32:41.269530', '2026-09-22T06:27:50.602000') ON CONFLICT DO NOTHING;

INSERT INTO public.conversation_messages ("id", "conversation_id", "role", "content", "metadata", "token_count", "created_at") VALUES (1, 1, 'user', '如何使用灭火器扑救初期火灾？', '{}', 14, '2026-09-22T14:26:42.425886') ON CONFLICT DO NOTHING;
INSERT INTO public.conversation_messages ("id", "conversation_id", "role", "content", "metadata", "token_count", "created_at") VALUES (2, 1, 'user', '你好，请简要介绍可燃物、助燃物和着火源', '{}', 19, '2026-09-22T14:27:47.987886') ON CONFLICT DO NOTHING;
INSERT INTO public.conversation_messages ("id", "conversation_id", "role", "content", "metadata", "token_count", "created_at") VALUES (3, 1, 'assistant', '### 一、可燃物
指能与空气中的氧或其他氧化剂发生燃烧反应的物质，比如木材、纸张、汽油、天然气、塑料等，是燃烧的物质基础。
### 二、助燃物
主要是指氧气（空气中氧含量约21%即可维持燃烧），也包括氧化剂类物质比如氯气、高锰酸钾等，能够支持和帮助可燃物持续燃烧。
### 三、着火源
指使可燃物与助燃物发生燃烧反应的能量来源，常见的有明火、电火花、高温表面、摩擦撞击产生的热量、自燃发热等。

燃烧的发生必须同时具备这三个要素，缺一不可。', '{}', 221, '2026-09-22T14:27:50.480580') ON CONFLICT DO NOTHING;

INSERT INTO public.events ("id", "event_no", "plan_id", "title", "description", "level", "status", "location", "trigger_type", "started_at", "resolved_at", "closed_at", "created_by", "created_at", "updated_at") VALUES (1, 'EV20260920001', 1, 'A栋3楼烟雾告警', 'A栋3楼走廊检测到烟雾浓度超标', 'high', 'resolved', 'A栋3楼走廊', 'auto', '2026-09-20T23:19:13.193653', NULL, NULL, 1, '2026-09-20T23:19:13.193653', '2026-09-20T23:19:13.193653') ON CONFLICT DO NOTHING;
INSERT INTO public.events ("id", "event_no", "plan_id", "title", "description", "level", "status", "location", "trigger_type", "started_at", "resolved_at", "closed_at", "created_by", "created_at", "updated_at") VALUES (2, 'EV20260920002', 2, 'B栋1号电梯故障', 'B栋1号电梯运行中突然停止，有人员被困', 'critical', 'active', 'B栋1号电梯', 'auto', '2026-09-20T23:19:13.193653', NULL, NULL, 2, '2026-09-20T23:19:13.193653', '2026-09-20T23:19:13.193653') ON CONFLICT DO NOTHING;

INSERT INTO public.event_ai_reports ("id", "event_id", "summary", "timeline", "analysis", "suggestions", "generated_at", "created_at") VALUES (1, 1, 'A栋3楼走廊发生烟雾告警事件，系统自动触发火灾应急预案，经过现场处置确认火情已解除。', '14:00 烟雾探测器触发告警\n14:05 系统自动通知相关人员\n14:10 现场人员到达确认\n14:30 火情解除\n14:35 事件归档', '本次事件响应及时，从告警触发到人员到达现场仅用10分钟。烟雾探测器灵敏度正常，未发现误报情况。', '1. 建议增加该楼层灭火器配备\n2. 建议每季度进行一次消防演练\n3. 建议检查相邻楼层的烟雾探测器状态', '2026-09-20T23:19:13.193653', '2026-09-20T23:19:13.193653') ON CONFLICT DO NOTHING;

INSERT INTO public.event_node_progress ("id", "event_id", "node_id", "node_type", "node_name", "status", "started_at", "completed_at", "operator_id", "remark", "created_at") VALUES (1, 1, 1, 'trigger', '火警触发', 'completed', '2026-09-20T21:19:13.193653', '2026-09-20T21:19:13.193653', NULL, NULL, '2026-09-20T23:19:13.193653') ON CONFLICT DO NOTHING;
INSERT INTO public.event_node_progress ("id", "event_id", "node_id", "node_type", "node_name", "status", "started_at", "completed_at", "operator_id", "remark", "created_at") VALUES (2, 1, 2, 'notification', '通知相关人员', 'completed', '2026-09-20T21:24:13.193653', '2026-09-20T21:29:13.193653', NULL, NULL, '2026-09-20T23:19:13.193653') ON CONFLICT DO NOTHING;
INSERT INTO public.event_node_progress ("id", "event_id", "node_id", "node_type", "node_name", "status", "started_at", "completed_at", "operator_id", "remark", "created_at") VALUES (3, 1, 3, 'task', '现场处置任务', 'completed', '2026-09-20T21:29:13.193653', '2026-09-20T22:19:13.193653', 3, NULL, '2026-09-20T23:19:13.193653') ON CONFLICT DO NOTHING;
INSERT INTO public.event_node_progress ("id", "event_id", "node_id", "node_type", "node_name", "status", "started_at", "completed_at", "operator_id", "remark", "created_at") VALUES (4, 1, 4, 'escalation', '人工升级确认', 'completed', '2026-09-20T22:19:13.193653', '2026-09-20T22:24:13.193653', 1, NULL, '2026-09-20T23:19:13.193653') ON CONFLICT DO NOTHING;
INSERT INTO public.event_node_progress ("id", "event_id", "node_id", "node_type", "node_name", "status", "started_at", "completed_at", "operator_id", "remark", "created_at") VALUES (5, 1, 5, 'end', '事件结束', 'completed', '2026-09-20T22:24:13.193653', '2026-09-20T22:29:13.193653', 1, NULL, '2026-09-20T23:19:13.193653') ON CONFLICT DO NOTHING;
INSERT INTO public.event_node_progress ("id", "event_id", "node_id", "node_type", "node_name", "status", "started_at", "completed_at", "operator_id", "remark", "created_at") VALUES (6, 2, 5, 'trigger', '电梯故障触发', 'completed', '2026-09-20T22:49:13.193653', '2026-09-20T22:49:13.193653', NULL, NULL, '2026-09-20T23:19:13.193653') ON CONFLICT DO NOTHING;
INSERT INTO public.event_node_progress ("id", "event_id", "node_id", "node_type", "node_name", "status", "started_at", "completed_at", "operator_id", "remark", "created_at") VALUES (7, 2, 6, 'notification', '通知维保人员', 'completed', '2026-09-20T22:54:13.193653', '2026-09-20T22:59:13.193653', NULL, NULL, '2026-09-20T23:19:13.193653') ON CONFLICT DO NOTHING;
INSERT INTO public.event_node_progress ("id", "event_id", "node_id", "node_type", "node_name", "status", "started_at", "completed_at", "operator_id", "remark", "created_at") VALUES (8, 2, 7, 'task', '救援任务', 'in_progress', '2026-09-20T22:59:13.193653', NULL, 3, NULL, '2026-09-20T23:19:13.193653') ON CONFLICT DO NOTHING;

INSERT INTO public.event_tasks ("id", "event_id", "node_id", "title", "description", "assignee_id", "status", "priority", "due_at", "completed_at", "created_at", "updated_at") VALUES (1, 1, 3, '确认火情', NULL, 2, 'completed', 'high', NULL, NULL, '2026-09-20T23:19:13.193653', '2026-09-20T23:19:13.193653') ON CONFLICT DO NOTHING;
INSERT INTO public.event_tasks ("id", "event_id", "node_id", "title", "description", "assignee_id", "status", "priority", "due_at", "completed_at", "created_at", "updated_at") VALUES (2, 1, 3, '疏散楼层人员', NULL, 2, 'completed', 'high', NULL, NULL, '2026-09-20T23:19:13.193653', '2026-09-20T23:19:13.193653') ON CONFLICT DO NOTHING;
INSERT INTO public.event_tasks ("id", "event_id", "node_id", "title", "description", "assignee_id", "status", "priority", "due_at", "completed_at", "created_at", "updated_at") VALUES (3, 1, 3, '启动消防设备', NULL, 3, 'completed', 'high', NULL, NULL, '2026-09-20T23:19:13.193653', '2026-09-20T23:19:13.193653') ON CONFLICT DO NOTHING;
INSERT INTO public.event_tasks ("id", "event_id", "node_id", "title", "description", "assignee_id", "status", "priority", "due_at", "completed_at", "created_at", "updated_at") VALUES (4, 2, 7, '确认困人情况', NULL, 2, 'completed', 'high', NULL, NULL, '2026-09-20T23:19:13.193653', '2026-09-20T23:19:13.193653') ON CONFLICT DO NOTHING;
INSERT INTO public.event_tasks ("id", "event_id", "node_id", "title", "description", "assignee_id", "status", "priority", "due_at", "completed_at", "created_at", "updated_at") VALUES (5, 2, 7, '联系电梯维保', NULL, 3, 'in_progress', 'high', NULL, NULL, '2026-09-20T23:19:13.193653', '2026-09-20T23:19:13.193653') ON CONFLICT DO NOTHING;
INSERT INTO public.event_tasks ("id", "event_id", "node_id", "title", "description", "assignee_id", "status", "priority", "due_at", "completed_at", "created_at", "updated_at") VALUES (6, 2, 7, '现场安抚被困人员', NULL, 2, 'pending', 'medium', NULL, NULL, '2026-09-20T23:19:13.193653', '2026-09-20T23:19:13.193653') ON CONFLICT DO NOTHING;

INSERT INTO public.event_notifications ("id", "event_id", "node_id", "channel", "title", "content", "recipient_id", "status", "sent_at", "delivered_at", "error_message", "created_at") VALUES (1, 1, 2, 'sms', '【紧急】A栋3楼火灾告警', 'A栋3楼走廊检测到烟雾浓度超标，请立即前往处理', 1, 'sent', '2026-09-20T21:24:13.193653', NULL, NULL, '2026-09-20T23:19:13.193653') ON CONFLICT DO NOTHING;
INSERT INTO public.event_notifications ("id", "event_id", "node_id", "channel", "title", "content", "recipient_id", "status", "sent_at", "delivered_at", "error_message", "created_at") VALUES (2, 1, 2, 'sms', '【紧急】A栋3楼火灾告警', 'A栋3楼走廊检测到烟雾浓度超标，请立即前往处理', 2, 'sent', '2026-09-20T21:24:13.193653', NULL, NULL, '2026-09-20T23:19:13.193653') ON CONFLICT DO NOTHING;
INSERT INTO public.event_notifications ("id", "event_id", "node_id", "channel", "title", "content", "recipient_id", "status", "sent_at", "delivered_at", "error_message", "created_at") VALUES (3, 1, 2, 'app', '【紧急】A栋3楼火灾告警', 'A栋3楼走廊检测到烟雾浓度超标，请立即前往处理', 3, 'delivered', '2026-09-20T21:24:13.193653', NULL, NULL, '2026-09-20T23:19:13.193653') ON CONFLICT DO NOTHING;
INSERT INTO public.event_notifications ("id", "event_id", "node_id", "channel", "title", "content", "recipient_id", "status", "sent_at", "delivered_at", "error_message", "created_at") VALUES (4, 2, 6, 'sms', '【紧急】B栋电梯故障', 'B栋1号电梯故障，有人员被困，请立即前往救援', 3, 'sent', '2026-09-20T22:54:13.193653', NULL, NULL, '2026-09-20T23:19:13.193653') ON CONFLICT DO NOTHING;
