#!/usr/bin/env python3
"""从 Coze Supabase 开发库导出完整 DB 初始化 SQL（表+约束+索引+RLS+序列+种子数据）。"""
import psycopg2, sys

def get_url():
    try:
        from coze_workload_identity import Client
        client = Client()
        for e in client.get_project_env_vars():
            if e.key.upper() == "PGDATABASE_URL":
                return e.value
        client.close()
    except Exception as ex:
        sys.exit("ERR identity: %s" % ex)
    sys.exit("PGDATABASE_URL not found")

def esc(v):
    if v is None: return "NULL"
    if isinstance(v, bool): return "TRUE" if v else "FALSE"
    if isinstance(v, (int, float)): return str(v)
    import datetime, decimal
    if isinstance(v, (datetime.datetime, datetime.date)):
        return "'%s'" % v.isoformat()
    if isinstance(v, (dict, list)):
        # jsonb 列：用 json.dumps 生成合法 JSON（双引号），再对 SQL 单引号转义
        import json
        return "'" + json.dumps(v, ensure_ascii=False, separators=(',', ':')).replace("'", "''") + "'"
    return "'" + str(v).replace("'", "''") + "'"

def main():
    url = get_url()
    conn = psycopg2.connect(url)
    cur = conn.cursor()
    out = []

    out.append("-- ============================================================")
    out.append("-- 智慧园区专家问答策略系统 - 完整数据库初始化脚本（从线上库导出）")
    out.append("-- 适用: PostgreSQL 15+（含 pgvector 扩展）")
    out.append("-- 执行方式: Supabase SQL Editor 或 psql -f db/init.sql")
    out.append("-- ============================================================")
    out.append("")
    out.append("-- 扩展")
    out.append("CREATE EXTENSION IF NOT EXISTS vector;")
    out.append("CREATE EXTENSION IF NOT EXISTS pgcrypto;")
    out.append("CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";")
    out.append("")

    # 业务函数
    cur.execute("SELECT pg_get_functiondef(p.oid) FROM pg_proc p "
                "JOIN pg_namespace n ON n.oid=p.pronamespace "
                "WHERE n.nspname='public' AND p.proname='match_knowledge_chunks'")
    r = cur.fetchone()
    if r:
        out.append("-- RAG 向量相似度检索函数")
        out.append(r[0] + ";")
        out.append("")

    cur.execute("SELECT table_name FROM information_schema.tables "
                "WHERE table_schema='public' AND table_type='BASE TABLE' ORDER BY table_name")
    tables = [t[0] for t in cur.fetchall() if t[0] != 'health_check']

    def get_constraints(rel, contype):
        cur.execute("SELECT con.conname, pg_get_constraintdef(con.oid) "
                    "FROM pg_constraint con "
                    "JOIN pg_class c ON c.oid=con.conrelid "
                    "JOIN pg_namespace n ON n.oid=con.connamespace "
                    "WHERE n.nspname='public' AND c.relname=%s AND con.contype=%s "
                    "ORDER BY con.conname", (rel, contype))
        return cur.fetchall()

    import re
    def strip_prefix(defn, kw):
        # pg_get_constraintdef 形如 "FOREIGN KEY (a) REFERENCES b" / "UNIQUE (a)" / "CHECK (expr)"
        # 模板已写前缀关键字，这里只取括号主体
        s = defn.strip()
        if s.startswith(kw + ' '):
            s = s[len(kw):].strip()
        return s

    foreign_keys = {}

    for t in tables:
        cur.execute("SELECT c.column_name, c.data_type, c.udt_name, c.is_nullable, c.column_default, a.attidentity "
                    "FROM information_schema.columns c "
                    "JOIN pg_attribute a ON a.attrelid = c.table_name::regclass AND a.attname = c.column_name "
                    "WHERE c.table_schema='public' AND c.table_name=%s ORDER BY c.ordinal_position", (t,))
        cols = cur.fetchall()

        cur.execute("""SELECT a.attname FROM pg_index i
                       JOIN pg_class c ON c.oid=i.indrelid
                       JOIN pg_attribute a ON a.attrelid=c.oid AND a.attnum=ANY(i.indkey)
                       JOIN pg_namespace n ON n.oid=c.relnamespace
                       WHERE n.nspname='public' AND c.relname=%s AND i.indisprimary""", (t,))
        pk = [x[0] for x in cur.fetchall()]

        out.append("-- ================= TABLE: %s =================" % t)
        out.append("CREATE TABLE IF NOT EXISTS public.%s (" % t)
        defs = []
        for name, dt, udt, nullable, dflt, attidentity in cols:
            line = "    %s" % name
            if t == 'knowledge_chunks' and name == 'embedding':
                line += " vector(1024) NOT NULL"  # 修正：声明固定维度以便建 HNSW 索引
            else:
                line += " %s" % udt
            if name in pk and 'nextval(' in (dflt or ''):
                line += " GENERATED BY DEFAULT AS IDENTITY"  # 用 identity 取代旧式 serial，允许显式插值且自动增长
            if nullable == 'NO':
                line += " NOT NULL"
            if dflt and not ('nextval(' in dflt and name in pk):
                line += " DEFAULT %s" % dflt
            defs.append(line)
        if pk:
            defs.append("    PRIMARY KEY (%s)" % ", ".join(pk))
        out.append(",\n".join(defs) + "\n);")

        # 去重：按列引用去重外键，保留其中一个
        seen_fk = set()
        for cn, cd in get_constraints(t, 'u'):
            out.append("ALTER TABLE ONLY public.%s ADD CONSTRAINT %s UNIQUE %s;" % (t, cn, strip_prefix(cd, 'UNIQUE')))
        for cn, cd in get_constraints(t, 'c'):
            out.append("ALTER TABLE ONLY public.%s ADD CONSTRAINT %s CHECK %s;" % (t, cn, strip_prefix(cd, 'CHECK')))
        fks = get_constraints(t, 'f')
        fk_list = []
        for cn, cd in fks:
            # cd 形如 "FOREIGN KEY (a,b) REFERENCES x(y) [ON DELETE ..]"
            body = strip_prefix(cd, 'FOREIGN KEY')
            sig = re.sub(r'\s+', ' ', body).strip()
            if sig in seen_fk:
                continue
            seen_fk.add(sig)
            fk_list.append((cn, body))
        foreign_keys[t] = fk_list
        for cn, body in fk_list:
            out.append("ALTER TABLE ONLY public.%s ADD CONSTRAINT %s FOREIGN KEY %s;" % (t, cn, body))

        # 索引（排除主键，排除与约束同名的唯一索引，vector 索引转 HNSW）
        cur.execute("SELECT indexname, indexdef FROM pg_indexes "
                    "WHERE schemaname='public' AND tablename=%s ORDER BY indexname", (t,))
        # 收集该表已由约束创建的唯一索引名
        cur.execute("""SELECT c.conname FROM pg_constraint c JOIN pg_namespace n ON n.oid=c.connamespace
                       WHERE c.conrelid=(SELECT oid FROM pg_class WHERE relname=%s) AND c.contype IN ('u','p')""", (t,))
        constraint_idx = {r[0] for r in cur.fetchall()}
        cur2 = conn.cursor()
        cur2.execute("""SELECT indexname, indexdef FROM pg_indexes
                    WHERE schemaname='public' AND tablename=%s ORDER BY indexname""", (t,))
        for iname, idef in cur2.fetchall() or []:
            if iname.endswith('_pkey') or iname in constraint_idx:
                continue
            if 'ivfflat' in idef:
                # 转换为 HNSW：参数改用 m / ef_construction，适配向量检索（更准更适合小规模数据）
                idef = re.sub(r"USING ivfflat", "USING hnsw", idef)
                idef = re.sub(r" WITH \(lists='\d+'\)", " WITH (m=16, ef_construction=64)", idef)
            out.append(idef + ";")
        out.append("")

    # 序列校准（把序列当前位置设为 max(id)+1）
    out.append("-- ============ 序列值校准 ============")
    for t in tables:
        seq = None
        try:
            cur.execute("SELECT pg_get_serial_sequence('public.%s','id')" % t)
            seq = cur.fetchone()[0]
        except Exception:
            pass
        if seq:
            out.append("SELECT setval('%s', COALESCE((SELECT MAX(id) FROM public.%s), 1), true);" % (seq, t))
    out.append("")

    # RLS
    cur.execute("SELECT c.relname FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace "
                "WHERE n.nspname='public' AND c.relrowsecurity ORDER BY relname")
    rls_tables = [x[0] for x in cur.fetchall()]
    if rls_tables:
        out.append("-- ============ RLS 策略 ============")
        for t in rls_tables:
            out.append("ALTER TABLE public.%s ENABLE ROW LEVEL SECURITY;" % t)
        out.append("")

    # 种子数据（拓扑顺序插入：被引用表在前）
    def load_rows(tbl):
        cur.execute('SELECT * FROM public.%s ORDER BY 1' % tbl)
        cols = [d[0] for d in cur.description]
        return cols, cur.fetchall()

    # 依赖顺序：departments -> contacts -> 依赖 contacts 的基础表 -> 类推
    data_tables = ['departments',
        'contacts',
        'emergency_plans',
        'message_templates',
        'knowledge_bases',
        'device_sources',
        'work_orders',
        'message_records',
        'work_order_logs',
        'knowledge_documents',
        'devices',
        'metric_mappings',
        'knowledge_chunks',
        'device_telemetry',
        'dashboard_configs',
        'emergency_plan_nodes',
        'emergency_plan_triggers',
        'conversations',
        'conversation_messages',
        'events',
        'event_ai_reports',
        'event_node_progress',
        'event_tasks',
        'event_notifications']

    out.append("-- ============ 种子数据 ============")
    for t in data_tables:
        try:
            cols, rows = load_rows(t)
        except Exception:
            continue
        if not rows:
            continue
        colsql = ", ".join('"%s"' % c for c in cols)
        for row in rows:
            vals = ", ".join(esc(v) for v in row)
            out.append("INSERT INTO public.%s (%s) VALUES (%s) ON CONFLICT DO NOTHING;" % (t, colsql, vals))
        out.append("")

    with open('db/init.sql', 'w', encoding='utf-8') as f:
        f.write("\n".join(out))
    print("WROTE db/init.sql lines=%d" % len(out))
    conn.close()

def iname_part(t):
    return t

if __name__ == '__main__':
    main()